#!/usr/bin/env python3
"""Download the variable woff2 files for the deck's two webfonts from Google
Fonts and emit a local fonts.css, so the presentation renders correctly with
no network connection (conference Wi-Fi is not to be trusted).

Re-run this if you ever change the type choices. Safe to delete afterwards;
it is a build helper, not a runtime dependency."""
import os
import re
import urllib.request

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
OUT = os.path.dirname(os.path.abspath(__file__))

# Variable-font requests (full weight ranges + italics).
#   EB Garamond  — scholarly French humanist book serif (display + body).
#   Libre Franklin — the free Franklin Gothic: the newspaper-gothic "label"
#                    voice for kickers, running heads, folios and footer chrome.
FAMILIES = {
    "EB Garamond": "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap",
    "Libre Franklin": "https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,100..900;1,100..900&display=swap",
}
KEEP = {"latin", "latin-ext"}  # covers French/German diacritics; skip the rest


def get(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30
    ).read()


faces = []
for family, url in FAMILIES.items():
    css = get(url).decode("utf-8")
    slug = family.lower().replace(" ", "")
    # Google precedes every @font-face with a `/* subset */` comment.
    parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    i = 1
    while i < len(parts) - 1:
        subset, block = parts[i].strip(), parts[i + 1]
        i += 2
        if subset not in KEEP:
            continue
        m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not m:
            continue
        woff_url = m.group(1)
        style = (re.search(r"font-style:\s*(\w+)", block) or [None, "normal"])[1]
        fname = f"{slug}-{style}-{subset}.woff2"
        open(os.path.join(OUT, fname), "wb").write(get(woff_url))
        faces.append(f"/* {family} · {style} · {subset} */"
                     + block.replace(woff_url, f"./{fname}").rstrip())
        print(f"  saved {fname}")

open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8").write(
    "/* Generated by fetch-fonts.py — self-hosted variable fonts. */\n"
    + "\n".join(faces) + "\n"
)
print(f"wrote fonts.css ({len(faces)} faces)")
