#!/usr/bin/env python3
"""Render the catalogue, deck metadata and static reading editions.

The static <ol class="talks"> in index.html is generated, so the list works
without JavaScript; the client-side search/filter enhancement reads the data-*
attributes each row carries. The block sits between marker comments:

    <!-- TALKS:START (generated by tools/build-index.py — edit talks/talks.json) -->
    …
    <!-- TALKS:END -->

Each published talk also receives read.html generated from its public slide
content, with local assets and text embeds. Edit index.html, never read.html.

Usage:
  python3 tools/build-index.py           # regenerate catalogue and readers
  python3 tools/build-index.py --check   # exit 1 if generated output is stale
"""
import argparse
import html
import os
import re
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
if TOOLS not in sys.path:
    sys.path.insert(0, TOOLS)

from slideslib.deck_metadata import sync_deck_html
from slideslib.manifest import ManifestValidationError, atomic_write, load_manifest
from slideslib.reader import render_reader

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
MANIFEST = os.path.join(ROOT, "talks", "talks.json")

START = "<!-- TALKS:START (generated by tools/build-index.py — edit talks/talks.json) -->"
END = "<!-- TALKS:END -->"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

ARROW = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
         'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
         '<path d="M5 12h14M13 6l6 6-6 6"/></svg>')


def fmt_date(iso):
    y, m, d = (int(x) for x in iso.split("-"))
    return f"{d:02d} {MONTHS[m - 1]} {y}"


def esc(s):
    return html.escape(str(s), quote=True)


def render_talk(t, number=1):
    """One row. `number` is the talk's place in the archive counted from the
    first talk, so it stays the talk's own when later talks are added or the
    list is filtered — a number that identifies, not a position."""
    slug = esc(t["slug"])
    topic_tags = list(dict.fromkeys("AI" if tag.upper() in {"AI", "IA"} else tag for tag in t.get("tags", [])))
    tags = "|".join(topic_tags)
    # Everything a reader might remember a talk by: the fuller in-deck title,
    # the venue line and the topic tags as well as what the row shows.
    search = " ".join([t.get("title", ""), t.get("deckTitle", ""), t.get("event", ""),
                       t.get("venue", ""), t.get("description", ""),
                       " ".join(t.get("presenters", [])), " ".join(t.get("tags", [])),
                       "AI IA artificial intelligence intelligence artificielle" if "AI" in topic_tags else ""]).lower()
    lang_label = {"en": "English", "fr": "Français"}.get(t["language"], t["language"])
    extras = [f'<span class="talk-presenters">{esc(" · ".join(t.get("presenters", [])))}</span>',
              f'<span class="talk-lang" title="{esc(lang_label)}">{esc(t["language"].upper())}</span>',
              f'<a href="talks/{slug}/read.html">Read</a>',
              f'<a href="{esc(t.get("pdf") or "talks/" + t["slug"] + "/slides.pdf")}">PDF</a>']
    if t.get("slideCount") is not None:
        extras.insert(2, f'<span class="talk-length">{t["slideCount"]} slide{"s" if t["slideCount"] != 1 else ""}</span>')
    if t.get("durationMinutes"):
        extras.insert(2, f'<span class="talk-duration">{t["durationMinutes"]} min</span>')
    if t.get("video"):
        extras.append(f'<a href="{esc(t["video"])}" target="_blank" rel="noopener">Video</a>')
    if t.get("eventUrl"):
        extras.append(f'<a href="{esc(t["eventUrl"])}" target="_blank" rel="noopener">Event</a>')
    return f"""      <li class="talk" data-lang="{esc(t['language'])}" data-year="{t['date'][:4]}" data-tags="{esc(tags)}" data-search="{esc(search)}">
        <a class="talk-row" href="talks/{slug}/" data-no="{number:02d}">
          <p class="talk-event">{esc(t['event'])}</p>
          <span class="talk-date">{fmt_date(t['date'])}</span>
          <h3 class="talk-title">{esc(t['title'])}</h3>
          <span class="talk-go">Open {ARROW}</span>
          <p class="talk-desc">{esc(t['description'])}</p>
        </a>
        <p class="talk-extras">{' · '.join(extras)}</p>
      </li>"""


def build_block(manifest):
    talks = sorted(manifest["talks"], key=lambda t: t["date"], reverse=True)
    n = len(talks)
    rows = "\n".join(render_talk(t, n - i) for i, t in enumerate(talks))
    return f"""{START}
      <div class="index-head">
        <h2 class="label">The talks</h2>
        <span class="count" id="talk-count" role="status" aria-live="polite" aria-atomic="true" data-total="{n}">{n:02d} talk{'s' if n != 1 else ''}</span>
      </div>
      <ol class="talks" id="talk-list">
{rows}
      </ol>
      <p class="empty" id="no-match" hidden>No talks match. <button type="button" id="clear-filters">Clear filters</button></p>
      {END}"""


def build_sitemap(manifest):
    site = manifest.get("site", "https://slides.frederickmadore.com").rstrip("/")
    talks = sorted(manifest["talks"], key=lambda t: t["date"], reverse=True)
    # The landing page changes exactly when a talk is added, so its lastmod is
    # the newest talk's date.
    newest = f"<lastmod>{talks[0]['date']}</lastmod>" if talks else ""
    urls = [f"  <url><loc>{site}/</loc>{newest}</url>"]
    urls += [f"  <url><loc>{site}/talks/{esc(t['slug'])}/</loc><lastmod>{t['date']}</lastmod></url>"
             for t in talks]
    urls += [f"  <url><loc>{site}/talks/{esc(t['slug'])}/read.html</loc><lastmod>{t['date']}</lastmod></url>"
             for t in talks]
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(urls) + "\n</urlset>\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify catalogue, metadata and reading editions are in sync")
    args = ap.parse_args(argv)

    try:
        manifest_model = load_manifest(MANIFEST)
    except ManifestValidationError as exc:
        for error in exc.errors:
            print(f"error: talks/talks.json: {error}")
        return 2
    manifest = manifest_model.to_dict()
    with open(INDEX, encoding="utf-8") as fh:
        page = fh.read()

    if START not in page or END not in page:
        sys.exit(f"error: {START!r} / {END!r} markers not found in index.html")

    sitemap = build_sitemap(manifest)
    sitemap_path = os.path.join(ROOT, "sitemap.xml")
    old_sitemap = ""
    if os.path.exists(sitemap_path):
        with open(sitemap_path, encoding="utf-8") as fh:
            old_sitemap = fh.read()

    deck_updates, reader_updates = [], []
    for talk, row in zip(manifest_model.talks, manifest["talks"]):
        path = os.path.join(ROOT, "talks", talk.slug, "index.html")
        if not os.path.exists(path):
            continue  # tools/audit.py reports the missing deck more precisely
        with open(path, encoding="utf-8") as fh:
            original = fh.read()
        try:
            rendered = sync_deck_html(original, talk, manifest_model.site, adopt_legacy=True)
            reader, slide_count = render_reader(rendered, talk, manifest_model.site,
                                               source_dir=os.path.dirname(path), root_dir=ROOT)
        except ValueError as exc:
            print(f"error: talks/{talk.slug}/index.html: {exc}")
            return 2
        if rendered != original:
            deck_updates.append((path, rendered))
        row["slideCount"] = slide_count
        reader_path = os.path.join(ROOT, "talks", talk.slug, "read.html")
        old_reader = ""
        if os.path.exists(reader_path):
            with open(reader_path, encoding="utf-8") as fh:
                old_reader = fh.read()
        if reader != old_reader:
            reader_updates.append((reader_path, reader))

    block = build_block(manifest)
    new_page = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block,
                      page, count=1, flags=re.DOTALL)

    if args.check:
        if new_page != page or sitemap != old_sitemap or deck_updates or reader_updates:
            stale = ["index.html/sitemap.xml"] if new_page != page or sitemap != old_sitemap else []
            stale.extend(os.path.relpath(path, ROOT) for path, _ in deck_updates)
            stale.extend(os.path.relpath(path, ROOT) for path, _ in reader_updates)
            print("generated files OUT OF DATE — run: python3 tools/build-index.py")
            for path in stale:
                print(f"  {path}")
            return 1
        print("index.html, sitemap.xml, deck metadata and reading editions are in sync")
        return 0

    if new_page != page:
        atomic_write(INDEX, new_page)
        print(f"index.html regenerated from {os.path.relpath(MANIFEST, ROOT)} "
              f"({len(manifest['talks'])} talks)")
    else:
        print("index.html already up to date")
    if sitemap != old_sitemap:
        atomic_write(sitemap_path, sitemap)
        print("sitemap.xml regenerated")
    for path, rendered in deck_updates:
        atomic_write(path, rendered)
        print(f"{os.path.relpath(path, ROOT)} metadata regenerated")
    for path, rendered in reader_updates:
        atomic_write(path, rendered)
        print(f"{os.path.relpath(path, ROOT)} reading edition regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
