#!/usr/bin/env python3
"""Render the landing page's talk list from the manifest (talks/talks.json).

The static <ol class="talks"> in index.html is generated, so the list works
without JavaScript; a JSON copy of the manifest is embedded alongside it for
the client-side search/filter enhancement. Both sit between marker comments:

    <!-- TALKS:START (generated by tools/build-index.py — edit talks/talks.json) -->
    …
    <!-- TALKS:END -->

Usage:
  python3 tools/build-index.py           # regenerate index.html in place
  python3 tools/build-index.py --check   # exit 1 if index.html is out of date
"""
import argparse
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
MANIFEST = os.path.join(ROOT, "talks", "talks.json")

START = "<!-- TALKS:START (generated by tools/build-index.py — edit talks/talks.json) -->"
END = "<!-- TALKS:END -->"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
          "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

ARROW = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
         'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
         '<path d="M5 12h14M13 6l6 6-6 6"/></svg>')


def fmt_date(iso):
    y, m, d = (int(x) for x in iso.split("-"))
    return f"{d:02d} {MONTHS[m - 1]} {y}"


def esc(s):
    return html.escape(str(s), quote=True)


def render_talk(t):
    slug = esc(t["slug"])
    tags = "|".join(t.get("tags", []))
    search = " ".join([t.get("title", ""), t.get("event", ""), t.get("description", ""),
                       " ".join(t.get("presenters", []))]).lower()
    lang_label = {"en": "English", "fr": "Français"}.get(t["language"], t["language"])
    extras = [f'<span class="talk-presenters">{esc(" · ".join(t.get("presenters", [])))}</span>',
              f'<span class="talk-lang" title="{esc(lang_label)}">{esc(t["language"].upper())}</span>',
              f'<a href="talks/{slug}/slides.pdf">PDF</a>',
              f'<a href="talks/{slug}/offline.zip" download>Offline copy</a>']
    if t.get("video"):
        extras.append(f'<a href="{esc(t["video"])}" target="_blank" rel="noopener">Video</a>')
    if t.get("eventUrl"):
        extras.append(f'<a href="{esc(t["eventUrl"])}" target="_blank" rel="noopener">Event</a>')
    return f"""      <li class="talk" data-lang="{esc(t['language'])}" data-year="{t['date'][:4]}" data-tags="{esc(tags)}" data-search="{esc(search)}">
        <a class="talk-row" href="talks/{slug}/">
          <p class="talk-event">{esc(t['event'])}</p>
          <span class="talk-date">{fmt_date(t['date'])}</span>
          <h3 class="talk-title">{esc(t['title'])}</h3>
          <span class="talk-go">Open {ARROW}</span>
          <p class="talk-desc">{esc(t['description'])}</p>
        </a>
        <p class="talk-extras">{' · '.join(extras)}</p>
      </li>"""


def build_block(manifest):
    talks = sorted(manifest["talks"], key=lambda t: t["date"], reverse=True)
    n = len(talks)
    rows = "\n".join(render_talk(t) for t in talks)
    data = json.dumps({"talks": talks}, ensure_ascii=False, separators=(",", ":"))
    # </script> cannot appear inside the JSON island
    data = data.replace("</", "<\\/")
    return f"""{START}
      <div class="index-head">
        <span class="label">The talks</span>
        <span class="count" id="talk-count" data-total="{n}">{n:02d} talk{'s' if n != 1 else ''}</span>
      </div>
      <ol class="talks" id="talk-list">
{rows}
      </ol>
      <p class="empty" id="no-match" hidden>No talks match — clear the filters to see all of them.</p>
      <script type="application/json" id="talk-data">{data}</script>
      {END}"""


def build_sitemap(manifest):
    site = manifest.get("site", "https://slides.frederickmadore.com").rstrip("/")
    talks = sorted(manifest["talks"], key=lambda t: t["date"], reverse=True)
    urls = [f"  <url><loc>{site}/</loc></url>"]
    urls += [f"  <url><loc>{site}/talks/{esc(t['slug'])}/</loc><lastmod>{t['date']}</lastmod></url>"
             for t in talks]
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(urls) + "\n</urlset>\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify index.html is in sync with talks/talks.json")
    args = ap.parse_args(argv)

    with open(MANIFEST, encoding="utf-8") as fh:
        manifest = json.load(fh)
    with open(INDEX, encoding="utf-8") as fh:
        page = fh.read()

    if START not in page or END not in page:
        sys.exit(f"error: {START!r} / {END!r} markers not found in index.html")

    block = build_block(manifest)
    new_page = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block,
                      page, count=1, flags=re.DOTALL)

    sitemap = build_sitemap(manifest)
    sitemap_path = os.path.join(ROOT, "sitemap.xml")
    old_sitemap = ""
    if os.path.exists(sitemap_path):
        with open(sitemap_path, encoding="utf-8") as fh:
            old_sitemap = fh.read()

    if args.check:
        if new_page != page or sitemap != old_sitemap:
            print("index.html/sitemap.xml OUT OF DATE — run: python3 tools/build-index.py")
            return 1
        print("index.html and sitemap.xml are in sync with talks/talks.json")
        return 0

    if new_page != page:
        with open(INDEX, "w", encoding="utf-8") as fh:
            fh.write(new_page)
        print(f"index.html regenerated from {os.path.relpath(MANIFEST, ROOT)} "
              f"({len(manifest['talks'])} talks)")
    else:
        print("index.html already up to date")
    if sitemap != old_sitemap:
        with open(sitemap_path, "w", encoding="utf-8") as fh:
            fh.write(sitemap)
        print("sitemap.xml regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
