#!/usr/bin/env python3
"""Build a SLIM, offline highlight.js for the deck.

The reveal.js highlight *plugin* we used to vendor bundles every language and
weighs ~921 KB. A talk needs a handful of grammars at most. This script pulls
highlight.js core plus only the LANGUAGES you list from the official
cdn-release ESM build, converts them to one classic <script> (exposing
`window.hljs`), and writes it to ../shared/highlight.min.js — typically
30-60 KB instead of 921 KB.

deck.js highlights every <pre><code> via `window.hljs`, so once this file is
loaded the bundled reveal highlight plugin is no longer needed (see README).

Re-run if you change LANGUAGES or VERSION. Build helper, not a runtime
dependency — needs a network connection once; safe to delete afterwards.

After writing, the generated file is syntax-checked (node --check when node
is available) and its version + sha256 are recorded in
shared/vendor-manifest.json so the provenance of the vendored bundle stays
auditable.
"""
import hashlib
import json
import os
import re
import subprocess
import urllib.request

# Pin a version so builds are reproducible. Bump deliberately.
VERSION = "11.11.1"
# Both serve the identical highlightjs/cdn-release tag; the first that
# responds wins (some networks block one CDN or the other).
MIRRORS = [
    f"https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@{VERSION}/build/es",
    f"https://raw.githubusercontent.com/highlightjs/cdn-release/{VERSION}/build/es",
]
BASE = MIRRORS[0]

# The grammars your slides actually use. Add/remove freely — each one is a few KB.
# Names must match highlight.js language ids (the filename under build/es/languages/).
LANGUAGES = [
    "bash",
    "python",
    "json",
    "javascript",
    "xml",        # also powers HTML
    "markdown",
    "yaml",
]

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "shared", "highlight.min.js")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")


def get(path: str) -> str:
    global BASE
    last = None
    for base in MIRRORS:
        try:
            text = urllib.request.urlopen(
                urllib.request.Request(f"{base}/{path}", headers={"User-Agent": UA}), timeout=30
            ).read().decode("utf-8")
            BASE = base
            return text
        except Exception as e:      # try the next mirror
            last = e
    raise last


def strip_exports(src: str) -> str:
    """Turn an ESM module's single default export into a `return`, so the
    module body can run inside an IIFE that yields that default value.
    highlight.js core and language modules export exactly one default and
    import nothing, which is what makes this safe."""
    src = re.sub(r"export\s*\{\s*([\w$]+)\s+as\s+default\s*\}\s*;?", r";return \1;", src)
    src = re.sub(r"export\s+default\s+", "return ", src)
    return src


print(f"highlight.js {VERSION} — core + {len(LANGUAGES)} language(s)")

core = strip_exports(get("core.min.js"))
chunks = [
    "/* Slim highlight.js — generated by tools/fetch-highlight.py. */",
    f"/* highlight.js {VERSION} · core + {', '.join(LANGUAGES)} */",
    "(function(){",
    "var hljs=(function(){" + core + "})();",
]
print("  core")

for lang in LANGUAGES:
    body = strip_exports(get(f"languages/{lang}.min.js"))
    chunks.append(
        'try{hljs.registerLanguage("%s",(function(){%s})());}catch(e){}' % (lang, body)
    )
    print(f"  + {lang}")

chunks.append("window.hljs=hljs;")
chunks.append("})();")

out = "\n".join(chunks) + "\n"
with open(OUT, "w", encoding="utf-8") as f:
    f.write(out)

# Verify the generated JavaScript actually parses before trusting it.
try:
    subprocess.run(["node", "--check", OUT], check=True)
    print("node --check: OK")
except FileNotFoundError:
    print("node not found — syntax check skipped (verify shared/highlight.min.js manually)")
except subprocess.CalledProcessError:
    raise SystemExit("generated highlight.min.js FAILED the node syntax check — not usable")

# Record provenance (source version + checksum) in the vendor manifest.
MANIFEST = os.path.join(os.path.dirname(OUT), "vendor-manifest.json")
manifest = {}
if os.path.exists(MANIFEST):
    with open(MANIFEST, encoding="utf-8") as f:
        manifest = json.load(f)
manifest["highlight.js"] = {
    "version": VERSION,
    "languages": LANGUAGES,
    "source": BASE,
    "file": "highlight.min.js",
    "sha256": hashlib.sha256(out.encode("utf-8")).hexdigest(),
}
with open(MANIFEST, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)
    f.write("\n")
print(f"vendor manifest updated: {os.path.relpath(MANIFEST)}")

print(f"\nwrote {os.path.relpath(OUT)}  ({len(out)/1024:.0f} KB, was ~921 KB)")
print("Talks load it via ../../shared/highlight.min.js (decks without code load nothing).")
