#!/usr/bin/env python3
"""Re-vendor the three variable webfonts and update their integrity manifest.

All remote responses are downloaded and validated in memory before any tracked
file changes. The final replacements are atomic per file and roll back to the
previous bytes if a filesystem write fails midway through the transaction.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "shared" / "fonts"
MANIFEST = ROOT / "shared" / "vendor-manifest.json"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

FAMILIES = {
    "EB Garamond": "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap",
    "Libre Franklin": "https://fonts.googleapis.com/css2?family=Libre+Franklin:ital,wght@0,100..900;1,100..900&display=swap",
    # The mono utility face. Italic is not optional here: highlight.js sets
    # comments and quotes in it, so without the italic subset every code
    # comment renders in a synthesised oblique.
    "JetBrains Mono": "https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap",
}
KEEP = {"latin", "latin-ext"}


def get(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        body = response.read()
    if not body:
        raise RuntimeError(f"empty response from {url}")
    return body


def atomic_bytes(path: Path, value: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(value)
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def build_outputs() -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    faces: list[str] = []
    for family, url in FAMILIES.items():
        css = get(url).decode("utf-8")
        slug = family.lower().replace(" ", "")
        parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
        for index in range(1, len(parts) - 1, 2):
            subset, block = parts[index].strip(), parts[index + 1]
            if subset not in KEEP:
                continue
            match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not match:
                raise RuntimeError(f"{family} {subset}: Google CSS contained no woff2 URL")
            font_url = match.group(1)
            style_match = re.search(r"font-style:\s*(\w+)", block)
            style = style_match.group(1) if style_match else "normal"
            filename = f"{slug}-{style}-{subset}.woff2"
            outputs[OUT / filename] = get(font_url)
            faces.append(
                f"/* {family} · {style} · {subset} */"
                + block.replace(font_url, f"./{filename}").rstrip()
            )
    expected = len(FAMILIES) * len(KEEP) * 2  # normal + italic for each subset
    if len(outputs) != expected:
        raise RuntimeError(f"expected {expected} font files, received {len(outputs)}")
    stylesheet = (
        "/* Generated by tools/fetch-fonts.py — self-hosted variable fonts. */\n"
        + "\n".join(faces) + "\n"
    )
    outputs[OUT / "fonts.css"] = stylesheet.encode("utf-8")
    return outputs


def main() -> int:
    outputs = build_outputs()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    files = sorted(path.relative_to(ROOT / "shared").as_posix() for path in outputs)
    manifest["google-fonts"] = {
        "source": list(FAMILIES.values()),
        "files": files,
        "sha256": {
            path.relative_to(ROOT / "shared").as_posix(): hashlib.sha256(value).hexdigest()
            for path, value in sorted(outputs.items(), key=lambda item: str(item[0]))
        },
    }
    manifest_bytes = (json.dumps(manifest, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    transaction = {**outputs, MANIFEST: manifest_bytes}
    backups = {path: path.read_bytes() if path.exists() else None for path in transaction}
    try:
        for path, value in transaction.items():
            atomic_bytes(path, value)
    except Exception:
        for path, value in backups.items():
            if value is None:
                path.unlink(missing_ok=True)
            else:
                atomic_bytes(path, value)
        raise
    for path in sorted(outputs):
        print(f"saved  {path.relative_to(ROOT)}")
    print("updated shared/vendor-manifest.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
