#!/usr/bin/env python3
"""Build a SLIM, offline highlight.js for the deck.

The reveal.js highlight *plugin* we used to vendor bundles every language and
weighs ~921 KB. A talk needs a handful of grammars at most. This script pulls
highlight.js core plus only the LANGUAGES you list from the official
cdn-release ESM build, converts them to one classic <script> (exposing
`window.hljs`), and writes it to ../shared/highlight.min.js — typically
30-60 KB instead of 921 KB.

deck.js highlights every <pre><code> via `window.hljs`, so once this file is
loaded the bundled reveal highlight plugin is no longer needed (see README).

Re-run if you change LANGUAGES or VERSION. Build helper, not a runtime
dependency — needs a network connection once; safe to delete afterwards.
"""
import os
import re
import urllib.request

# Pin a version so builds are reproducible. Bump deliberately.
VERSION = "11.10.0"
BASE = f"https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@{VERSION}/build/es"

# The grammars your slides actually use. Add/remove freely — each one is a few KB.
# Names must match highlight.js language ids (the filename under build/es/languages/).
LANGUAGES = [
    "bash",
    "python",
    "json",
    "javascript",
    "xml",        # also powers HTML
    "markdown",
    "yaml",
]

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "shared", "highlight.min.js")
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")


def get(url: str) -> str:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30
    ).read().decode("utf-8")


def strip_exports(src: str) -> str:
    """Turn an ESM module's single default export into a `return`, so the
    module body can run inside an IIFE that yields that default value.
    highlight.js core and language modules export exactly one default and
    import nothing, which is what makes this safe."""
    src = re.sub(r"export\s*\{\s*([\w$]+)\s+as\s+default\s*\}\s*;?", r";return \1;", src)
    src = re.sub(r"export\s+default\s+", "return ", src)
    return src


print(f"highlight.js {VERSION} — core + {len(LANGUAGES)} language(s)")

core = strip_exports(get(f"{BASE}/core.min.js"))
chunks = [
    "/* Slim highlight.js — generated by tools/fetch-highlight.py. */",
    f"/* highlight.js {VERSION} · core + {', '.join(LANGUAGES)} */",
    "(function(){",
    "var hljs=(function(){" + core + "})();",
]
print("  core")

for lang in LANGUAGES:
    body = strip_exports(get(f"{BASE}/languages/{lang}.min.js"))
    chunks.append(
        'try{hljs.registerLanguage("%s",(function(){%s})());}catch(e){}' % (lang, body)
    )
    print(f"  + {lang}")

chunks.append("window.hljs=hljs;")
chunks.append("})();")

out = "\n".join(chunks) + "\n"
with open(OUT, "w", encoding="utf-8") as f:
    f.write(out)

print(f"\nwrote {os.path.relpath(OUT)}  ({len(out)/1024:.0f} KB, was ~921 KB)")
print("Now load it in each talk instead of the bundled reveal highlight plugin:")
print('  <script src="../../shared/highlight.min.js"></script>')
print("and drop the <script src=\".../plugin/highlight.js\"> line.")
